name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Auroral0810
          
      - name: Push to main branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add profile-3d-contrib/
          git commit -m "Generated 3D Contribution Graph" || echo "No changes to commit"
          git push origin main || echo "No changes to push" 